-- MySQL Script generated by MySQL Workbench
-- 11/20/14 00:46:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Organizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Organizador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Organizador` (
  `DniOrg` VARCHAR(50) NOT NULL,
  `NombreOrg` VARCHAR(45) NOT NULL,
  `Telefono` INT(9) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DniOrg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pincho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pincho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pincho` (
  `NombrePincho` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `Precio` INT NOT NULL,
  `Ingredientes` VARCHAR(200) NOT NULL,
  `Fotos` VARCHAR(50) NOT NULL,
  `Informacion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`NombrePincho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Establecimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Establecimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Establecimiento` (
  `NombreEst` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Horaio` VARCHAR(45) NOT NULL,
  `Fotos` BLOB(512) NULL,
  `Web` VARCHAR(150) NULL,
  `Pincho_NombrePincho` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NombreEst`),
  INDEX `fk_Establecimiento_Pincho1_idx` (`Pincho_NombrePincho` ASC),
  CONSTRAINT `fk_Establecimiento_Pincho1`
    FOREIGN KEY (`Pincho_NombrePincho`)
    REFERENCES `mydb`.`Pincho` (`NombrePincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Concurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Concurso` (
  `NombreC` VARCHAR(50) NOT NULL,
  `FechaIni` DATETIME NOT NULL,
  `FechaFin` DATETIME NOT NULL,
  `BasesCon` VARCHAR(1000) NOT NULL,
  `Patrocinadores` VARCHAR(45) NULL,
  `Premios` VARCHAR(500) NULL,
  `Organizador_DniOrg` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NombreC`),
  INDEX `fk_Concurso_Organizador_idx` (`Organizador_DniOrg` ASC),
  CONSTRAINT `fk_Concurso_Organizador`
    FOREIGN KEY (`Organizador_DniOrg`)
    REFERENCES `mydb`.`Organizador` (`DniOrg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gastromapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gastromapa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gastromapa` (
  `NombreGas` VARCHAR(50) NOT NULL,
  `MapaUrl` VARCHAR(70) NOT NULL,
  `Concurso_NombreC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NombreGas`),
  INDEX `fk_Gastromapa_Concurso1_idx` (`Concurso_NombreC` ASC),
  CONSTRAINT `fk_Gastromapa_Concurso1`
    FOREIGN KEY (`Concurso_NombreC`)
    REFERENCES `mydb`.`Concurso` (`NombreC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jurado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jurado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jurado` (
  `DniJur` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Juradocol` VARCHAR(45) NULL,
  PRIMARY KEY (`DniJur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concurso_has_Jurado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Concurso_has_Jurado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Concurso_has_Jurado` (
  `Concurso_NombreC` VARCHAR(50) NOT NULL,
  `Jurado_DniJur` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Concurso_NombreC`, `Jurado_DniJur`),
  INDEX `fk_Concurso_has_Jurado_Jurado1_idx` (`Jurado_DniJur` ASC),
  INDEX `fk_Concurso_has_Jurado_Concurso1_idx` (`Concurso_NombreC` ASC),
  CONSTRAINT `fk_Concurso_has_Jurado_Concurso1`
    FOREIGN KEY (`Concurso_NombreC`)
    REFERENCES `mydb`.`Concurso` (`NombreC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concurso_has_Jurado_Jurado1`
    FOREIGN KEY (`Jurado_DniJur`)
    REFERENCES `mydb`.`Jurado` (`DniJur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pincho_has_Jurado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pincho_has_Jurado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pincho_has_Jurado` (
  `Pincho_NombrePincho` VARCHAR(50) NOT NULL,
  `Jurado_DniJur` VARCHAR(9) NOT NULL,
  `VotoPro` INT(2) NULL,
  PRIMARY KEY (`Pincho_NombrePincho`, `Jurado_DniJur`),
  INDEX `fk_Pincho_has_Jurado_Jurado1_idx` (`Jurado_DniJur` ASC),
  INDEX `fk_Pincho_has_Jurado_Pincho1_idx` (`Pincho_NombrePincho` ASC),
  CONSTRAINT `fk_Pincho_has_Jurado_Pincho1`
    FOREIGN KEY (`Pincho_NombrePincho`)
    REFERENCES `mydb`.`Pincho` (`NombrePincho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pincho_has_Jurado_Jurado1`
    FOREIGN KEY (`Jurado_DniJur`)
    REFERENCES `mydb`.`Jurado` (`DniJur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Establecimiento_has_Concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Establecimiento_has_Concurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Establecimiento_has_Concurso` (
  `Establecimiento_NombreEst` VARCHAR(50) NOT NULL,
  `Concurso_NombreC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Establecimiento_NombreEst`, `Concurso_NombreC`),
  INDEX `fk_Establecimiento_has_Concurso_Concurso1_idx` (`Concurso_NombreC` ASC),
  INDEX `fk_Establecimiento_has_Concurso_Establecimiento1_idx` (`Establecimiento_NombreEst` ASC),
  CONSTRAINT `fk_Establecimiento_has_Concurso_Establecimiento1`
    FOREIGN KEY (`Establecimiento_NombreEst`)
    REFERENCES `mydb`.`Establecimiento` (`NombreEst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Establecimiento_has_Concurso_Concurso1`
    FOREIGN KEY (`Concurso_NombreC`)
    REFERENCES `mydb`.`Concurso` (`NombreC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
